[package]
name = "demand"
version = "2.1.1"
edition = "2024"
description = "A CLI prompt library"
license = "MIT"
repository = "https://github.com/jdx/demand"
readme = "README.md"
keywords = ["cli", "prompt", "console"]
include = ["src/**/*", "examples/**/*", "README.md", "CHANGELOG.md", "LICENSE"]

[dependencies]
console = "0.16"
fuzzy-matcher = "0.3"
itertools = "0.15"
signal-hook = "0.4"
termcolor = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
ctor = "1"
indoc = "2"
insta = "1"

[target.'cfg(unix)'.dev-dependencies]
portable-pty = "0.9"
rio-vt = "0.5.1"

[profile.dev]
debug = 1
